import LanglandsFirstMainLemma.LocalField.Valuation
import LanglandsFirstMainLemma.LocalField.Lattices
import LanglandsFirstMainLemma.LocalField.ResidueField
import LanglandsFirstMainLemma.LocalField.Extension
import Mathlib.RingTheory.Nakayama

/-!
# Monogenic uniformizers

This file proves that every integral uniformizer generates the valuation ring of a finite
totally ramified extension of nonarchimedean local fields. Here total ramification is expressed
by `residueDegree F K = 1`.

The proof is finite and algebraic. If `C = 𝒪_F[π_K]`, equality of the residue fields says
that every element of `𝒪_K` is the sum of an element of `C` and a multiple of `π_K`. The
ring `𝒪_K` is finite over `C`. Moreover `π_K` belongs to the Jacobson radical of `C`: by
integrality, every maximal ideal of `C` lifts to a maximal ideal of the local ring `𝒪_K`,
and hence contains `π_K`. Nakayama's lemma then gives `C = 𝒪_K`.

This avoids choosing a special uniformizer and avoids an infinite expansion or completeness
argument.
-/

namespace LanglandsFirstMainLemma

open scoped Pointwise

section FiniteLocalAlgebra

variable {A B : Type*} [CommRing A] [CommRing B] [Algebra A B]
  [IsLocalRing B] [Module.Finite A B]

/-- A finite local algebra is generated by an element whose principal ideal is the maximal
ideal, provided every element can be approximated modulo that maximal ideal by the base ring.

This is the commutative-algebra core of the monogenic-uniformizer theorem. The apparent
iteration of residue lifting is absorbed by Nakayama's lemma over the intermediate algebra
`A[pi]`. The proof only needs the target to be local and finite over the base; no DVR or field
hypotheses occur here. -/
theorem algebra_adjoin_singleton_eq_top_of_finite_of_residue_lifts
    (pi : B)
    (hmax : IsLocalRing.maximalIdeal B = Ideal.span ({pi} : Set B))
    (hlift : ∀ b : B, ∃ a : A,
      b - algebraMap A B a ∈ IsLocalRing.maximalIdeal B) :
    Algebra.adjoin A ({pi} : Set B) = ⊤ := by
  let C : Subalgebra A B := Algebra.adjoin A ({pi} : Set B)

  -- Use the inclusion `C → B` as the intermediate algebra structure. The explicit scalar
  -- instance keeps the module structure definitionally aligned with that algebra map.
  letI : Algebra C B := C.toSubring.subtype.toAlgebra
  letI : SMul C B := Algebra.toSMul
  haveI : IsScalarTower A C B :=
    IsScalarTower.of_algebraMap_eq fun _ => rfl

  -- Any finite family of `A`-module generators is also a family of `C`-module generators.
  letI : Module.Finite C B :=
    Module.Finite.of_restrictScalars_finite A C B
  haveI : Algebra.IsIntegral C B := Algebra.IsIntegral.tower_top A

  let piC : C :=
    ⟨pi, Algebra.subset_adjoin (Set.mem_singleton pi)⟩
  let I : Ideal C := Ideal.span ({piC} : Set C)
  let N : Submodule C B := LinearMap.range (Algebra.linearMap C B)

  have hpiMax : pi ∈ IsLocalRing.maximalIdeal B := by
    rw [hmax]
    exact Ideal.subset_span (Set.mem_singleton pi)

  -- Every maximal ideal of `C` lifts through the integral inclusion to a maximal ideal of `B`.
  -- Since `B` is local, the lifted ideal is its unique maximal ideal and therefore contains
  -- `pi`. Thus the principal ideal `(pi)` of `C` lies in `Jac(C)`.
  have hJac : I ≤ Ideal.jacobson (⊥ : Ideal C) := by
    rw [Ideal.jacobson_bot, Ring.jacobson_eq_sInf_isMaximal]
    refine le_sInf fun m hm => ?_
    have hmMax : m.IsMaximal := hm
    letI : m.IsMaximal := hmMax
    have hinj : Function.Injective (algebraMap C B) :=
      C.toSubring.subtype_injective
    have hker : RingHom.ker (algebraMap C B) ≤ m := by
      rw [(RingHom.injective_iff_ker_eq_bot _).mp hinj]
      exact bot_le
    obtain ⟨Q, hQmax, hQcomap⟩ :=
      Ideal.exists_ideal_over_maximal_of_isIntegral (S := B) m hker
    rw [Ideal.span_singleton_le_iff_mem]
    rw [← hQcomap]
    have hQeq : Q = IsLocalRing.maximalIdeal B :=
      IsLocalRing.eq_maximalIdeal hQmax
    change pi ∈ Q
    rw [hQeq]
    exact hpiMax

  -- Residue lifting and principality of the maximal ideal give `B = C + pi * B`.
  have hdecomp : ∀ b : B, ∃ c : C, ∃ y : B,
      b = algebraMap C B c + algebraMap C B piC * y := by
    intro b
    obtain ⟨a, ha⟩ := hlift b
    rw [hmax, Ideal.mem_span_singleton] at ha
    obtain ⟨y, hy⟩ := ha
    refine ⟨algebraMap A C a, y, ?_⟩
    rw [← IsScalarTower.algebraMap_apply A C B]
    change b = algebraMap A B a + pi * y
    calc
      b = algebraMap A B a + (b - algebraMap A B a) := by ring
      _ = algebraMap A B a + pi * y := by rw [hy]

  have htop : (⊤ : Submodule C B) ≤ N ⊔ I • (⊤ : Submodule C B) := by
    intro b _
    obtain ⟨c, y, hby⟩ := hdecomp b
    have hc : algebraMap C B c ∈ N := ⟨c, rfl⟩
    have hpiI : piC ∈ I :=
      Ideal.subset_span (Set.mem_singleton piC)
    have hyTop : y ∈ (⊤ : Submodule C B) := Submodule.mem_top
    have hterm : algebraMap C B piC * y ∈ I • (⊤ : Submodule C B) := by
      have ht := Submodule.smul_mem_smul hpiI hyTop
      change algebraMap C B piC * y ∈ I • (⊤ : Submodule C B) at ht
      exact ht
    rw [hby]
    exact (N ⊔ I • (⊤ : Submodule C B)).add_mem
      ((show N ≤ N ⊔ I • (⊤ : Submodule C B) from le_sup_left) hc)
      ((show I • (⊤ : Submodule C B) ≤ N ⊔ I • (⊤ : Submodule C B)
        from le_sup_right) hterm)

  have htopN : (⊤ : Submodule C B) ≤ N :=
    Submodule.le_of_le_smul_of_le_jacobson_bot
      Module.Finite.fg_top hJac htop

  apply top_unique
  intro b _
  obtain ⟨c, hc⟩ := htopN (show b ∈ (⊤ : Submodule C B) by simp)
  change b ∈ C
  rw [← hc]
  exact c.property

end FiniteLocalAlgebra

section ResidueDegreeOne

variable (F K : Type*) [Field F] [Field K]
  [ValuativeRel F] [TopologicalSpace F] [IsNonarchimedeanLocalField F]
  [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
  [Algebra F K] [ValuativeExtension F K] [Module.Finite F K]

/-- Residue degree one makes the canonical residue-field map surjective. -/
theorem extensionResidueMap_surjective_of_residueDegree_eq_one
    (hf : residueDegree F K = 1) :
    Function.Surjective (extensionResidueMap F K) := by
  have hfin : Module.finrank (ResidueField F) (ResidueField K) = 1 := by
    rw [← residueDegree_eq_finrank_residueField F K, hf]
  exact (Algebra.finrank_eq_one_iff_bijective_algebraMap.mp hfin).2

/-- At residue degree one, every integral upper element has a lower integral lift modulo the
upper maximal ideal. -/
theorem exists_ringOfIntegers_sub_mem_maximalIdeal_of_residueDegree_eq_one
    (hf : residueDegree F K = 1) (b : ringOfIntegers K) :
    ∃ a : ringOfIntegers F,
      b - algebraMap (ringOfIntegers F) (ringOfIntegers K) a ∈
        IsLocalRing.maximalIdeal (ringOfIntegers K) := by
  have hres : Function.Surjective (extensionResidueMap F K) :=
    extensionResidueMap_surjective_of_residueDegree_eq_one F K hf
  obtain ⟨xi, hxi⟩ := hres (residueMap K b)
  obtain ⟨a, ha⟩ := residueMap_surjective F xi
  refine ⟨a, ?_⟩
  rw [← IsLocalRing.residue_eq_zero_iff]
  rw [map_sub]
  have halg :
      residueMap K
          (algebraMap (ringOfIntegers F) (ringOfIntegers K) a) =
        extensionResidueMap F K (residueMap F a) :=
    (Valuation.HasExtension.algebraMap_residue_eq_residue_algebraMap
      (ValuativeRel.valuation F) (ValuativeRel.valuation K) a).symm
  rw [halg, ha, hxi, sub_self]

/-- Every integral uniformizer generates the upper valuation ring over the lower valuation ring
in a finite residue-degree-one extension of nonarchimedean local fields. -/
theorem algebra_adjoin_uniformizer_eq_top_of_residueDegree_eq_one
    (hf : residueDegree F K = 1)
    (piK : ringOfIntegers K)
    (hpiK : (ValuativeRel.valuation K).IsUniformizer (piK : K)) :
    Algebra.adjoin (ringOfIntegers F)
      ({piK} : Set (ringOfIntegers K)) = ⊤ := by
  letI : Module.Finite (ringOfIntegers F) (ringOfIntegers K) :=
    ringOfIntegers_moduleFinite F K
  apply algebra_adjoin_singleton_eq_top_of_finite_of_residue_lifts
    piK hpiK.is_generator
  exact exists_ringOfIntegers_sub_mem_maximalIdeal_of_residueDegree_eq_one F K hf

/-- A finite residue-degree-one extension admits an integral uniformizer which generates its
valuation ring over the lower valuation ring. Existence is supplied by the canonical discrete
valuation; generation follows from the theorem for every uniformizer. -/
theorem exists_uniformizer_and_algebra_adjoin_eq_top_of_residueDegree_eq_one
    (hf : residueDegree F K = 1) :
    ∃ piK : ringOfIntegers K,
      (ValuativeRel.valuation K).IsUniformizer (piK : K) ∧
        Algebra.adjoin (ringOfIntegers F)
          ({piK} : Set (ringOfIntegers K)) = ⊤ := by
  obtain ⟨piK, hpiK⟩ :=
    Valuation.exists_isUniformizer_of_isCyclic_of_nontrivial
      (ValuativeRel.valuation K)
  exact ⟨piK, hpiK,
    algebra_adjoin_uniformizer_eq_top_of_residueDegree_eq_one F K hf piK hpiK⟩

/-- Blueprint-facing name for the existence of a monogenic integral uniformizer in a finite
residue-degree-one extension of nonarchimedean local fields. -/
theorem monogenicUniformizer (hf : residueDegree F K = 1) :
    ∃ piK : ringOfIntegers K,
      (ValuativeRel.valuation K).IsUniformizer (piK : K) ∧
        Algebra.adjoin (ringOfIntegers F)
          ({piK} : Set (ringOfIntegers K)) = ⊤ :=
  exists_uniformizer_and_algebra_adjoin_eq_top_of_residueDegree_eq_one F K hf

end ResidueDegreeOne

end LanglandsFirstMainLemma
