import LanglandsFirstMainLemma.Ramification.LowerGroups
import LanglandsFirstMainLemma.Delta.FirstMainStatement
import Mathlib.GroupTheory.SpecificGroups.Cyclic

/-!
# Cyclic extensions of prime degree

This file packages exactly the field-theoretic hypotheses used throughout the cyclic-prime
argument and derives the elementary interfaces that follow from them.  The extension degree,
Galois generator, ramification invariants, residue characteristic, lower filtration, and break
are never stored as independent data.

In particular, this file does not prove that a ramified prime-degree extension is totally
ramified, does not identify wild degree with residue characteristic, and contains no Herbrand,
different, trace-ideal, or norm-filtration theorem.  A nonnegative one-break index is constructed
only from the explicit hypothesis `G₀ = G`.
-/

noncomputable section

namespace LanglandsFirstMainLemma

/-- The raw ramification-side hypotheses for a finite cyclic Galois extension of prime degree.

The ambient field, algebra, and finite-module structures describe the extension.  Its sole
field reuses the theorem-level predicate `CyclicPrimeExtension`, whose three conjuncts are
precisely Galoisness, cyclicity of `Gal(K/F)`, and primality of the canonical degree
`Module.finrank F K`.  In particular there is no second copy of those hypotheses and no
separately stored degree, generator, ramification invariant, filtration, or break. -/
class PrimeCyclicExtension (F K : Type*) [Field F] [Field K] [Algebra F K]
    [Module.Free F K] [Module.Finite F K] : Prop where
  toCyclicPrimeExtension : CyclicPrimeExtension F K

namespace PrimeCyclicExtension

section Algebraic

variable (F K : Type*) [Field F] [Field K] [Algebra F K]
  [Module.Free F K] [Module.Finite F K]

/-- Construct the ramification-side package from the theorem-level cyclic-prime predicate
without unpacking and repacking its three conjuncts. -/
theorem ofCyclicPrimeExtension (h : CyclicPrimeExtension F K) : PrimeCyclicExtension F K :=
  ⟨h⟩

/-- The ramification package and the theorem-level cyclic-prime predicate carry exactly the
same mathematical hypotheses. -/
theorem iff_cyclicPrimeExtension :
    PrimeCyclicExtension F K ↔ CyclicPrimeExtension F K :=
  ⟨fun h => h.toCyclicPrimeExtension, ofCyclicPrimeExtension F K⟩

/-- A prime-cyclic package supplies the Galois instance required by the lower-filtration API. -/
instance instIsGalois [h : PrimeCyclicExtension F K] : IsGalois F K :=
  h.toCyclicPrimeExtension.1

/-- A prime-cyclic package supplies cyclicity of the actual Galois group `Gal(K/F)`. -/
instance instIsCyclic [h : PrimeCyclicExtension F K] : IsCyclic Gal(K/F) :=
  h.toCyclicPrimeExtension.2.1

/-- The extension degree is prime.  The degree is the canonical `Module.finrank`; no extra
natural number is chosen. -/
theorem degree_prime [h : PrimeCyclicExtension F K] :
    (Module.finrank F K).Prime :=
  h.toCyclicPrimeExtension.2.2

/-- The cardinality of the Galois group is the canonical extension degree. -/
theorem galoisCard_eq_degree [PrimeCyclicExtension F K] :
    Nat.card Gal(K/F) = Module.finrank F K :=
  IsGalois.card_aut_eq_finrank F K

/-- The Galois group has prime cardinality. -/
theorem galoisCard_prime [PrimeCyclicExtension F K] :
    (Nat.card Gal(K/F)).Prime := by
  rw [galoisCard_eq_degree F K]
  exact degree_prime F K

/-- The `Fact` form of prime Galois-group cardinality used by elementary subgroup lemmas. -/
instance instGaloisCardPrimeFact [PrimeCyclicExtension F K] :
    Fact (Nat.card Gal(K/F)).Prime :=
  ⟨galoisCard_prime F K⟩

/-- A noncomputably chosen generator of the cyclic Galois group. -/
noncomputable def generator [PrimeCyclicExtension F K] : Gal(K/F) :=
  Classical.choose (IsCyclic.exists_generator (α := Gal(K/F)))

/-- Every Galois automorphism lies in the subgroup generated by `generator`. -/
theorem generator_mem_zpowers [PrimeCyclicExtension F K] (σ : Gal(K/F)) :
    σ ∈ Subgroup.zpowers (generator F K) :=
  Classical.choose_spec (IsCyclic.exists_generator (α := Gal(K/F))) σ

/-- The chosen generator generates the whole Galois group. -/
theorem zpowers_generator [PrimeCyclicExtension F K] :
    Subgroup.zpowers (generator F K) = ⊤ := by
  rw [Subgroup.eq_top_iff']
  exact generator_mem_zpowers F K

/-- Power-surjectivity interface for the chosen Galois generator. -/
theorem exists_generator_zpow [PrimeCyclicExtension F K] (σ : Gal(K/F)) :
    ∃ n : ℤ, (generator F K) ^ n = σ :=
  Subgroup.mem_zpowers_iff.mp (generator_mem_zpowers F K σ)

/-- The order of the chosen generator is exactly the extension degree. -/
theorem orderOf_generator [PrimeCyclicExtension F K] :
    orderOf (generator F K) = Module.finrank F K := by
  rw [orderOf_eq_card_of_forall_mem_zpowers (generator_mem_zpowers F K),
    galoisCard_eq_degree F K]

/-- A prime-degree generator is nonidentity. -/
theorem generator_ne_one [PrimeCyclicExtension F K] :
    generator F K ≠ 1 := by
  intro hgen
  have horder : orderOf (generator F K) = 1 := orderOf_eq_one_iff.mpr hgen
  rw [orderOf_generator F K] at horder
  exact (degree_prime F K).ne_one horder

/-- The subgroup lattice of the nontrivial prime-order Galois group has distinct top and
bottom elements. -/
theorem galoisSubgroup_top_ne_bot [PrimeCyclicExtension F K] :
    (⊤ : Subgroup Gal(K/F)) ≠ ⊥ := by
  intro h
  have hmem : generator F K ∈ (⊥ : Subgroup Gal(K/F)) := by
    rw [← h]
    trivial
  exact generator_ne_one F K (Subgroup.mem_bot.mp hmem)

/-- Every subgroup of the prime-order Galois group is trivial or the whole group. -/
theorem subgroup_eq_bot_or_eq_top [PrimeCyclicExtension F K]
    (H : Subgroup Gal(K/F)) : H = ⊥ ∨ H = ⊤ :=
  Subgroup.eq_bot_or_eq_top_of_prime_card H

end Algebraic

section LocalInvariants

variable (F K : Type*) [Field F] [Field K]
  [ValuativeRel F] [TopologicalSpace F] [IsNonarchimedeanLocalField F]
  [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
  [Algebra F K] [ValuativeExtension F K]

/-- The canonical ramification index is positive. -/
theorem ramificationIndex_positive : 0 < ramificationIndex F K :=
  LanglandsFirstMainLemma.ramificationIndex_pos F K

/-- The canonical residue degree is positive. -/
theorem residueDegree_positive : 0 < residueDegree F K :=
  LanglandsFirstMainLemma.residueDegree_pos F K

/-- The extension degree is the product of the canonical ramification index and residue degree.
No prime-factor dichotomy is drawn here. -/
theorem degree_eq_ramificationIndex_mul_residueDegree [Module.Finite F K] :
    Module.finrank F K = ramificationIndex F K * residueDegree F K :=
  finrank_eq_ramificationIndex_mul_residueDegree F K

end LocalInvariants

end PrimeCyclicExtension

/-- The residue characteristic of a local field, kept as the canonical characteristic of its
canonical residue-field quotient. -/
abbrev residueCharacteristic (F : Type*) [Field F] [ValuativeRel F]
    [TopologicalSpace F] [IsNonarchimedeanLocalField F] : ℕ :=
  ringChar (ResidueField F)

/-- The residue characteristic of a nonarchimedean local field is prime. -/
theorem residueCharacteristic_prime (F : Type*) [Field F] [ValuativeRel F]
    [TopologicalSpace F] [IsNonarchimedeanLocalField F] :
    (residueCharacteristic F).Prime :=
  CharP.char_is_prime (ResidueField F) (residueCharacteristic F)

/-- A valuative extension has the same residue characteristic upstairs and downstairs. -/
theorem residueCharacteristic_extension_eq
    (F K : Type*) [Field F] [Field K]
    [ValuativeRel F] [TopologicalSpace F] [IsNonarchimedeanLocalField F]
    [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
    [Algebra F K] [ValuativeExtension F K] :
    residueCharacteristic K = residueCharacteristic F := by
  let p := residueCharacteristic F
  letI : CharP (ResidueField K) p :=
    (RingHom.charP_iff (algebraMap (ResidueField F) (ResidueField K))
      (algebraMap (ResidueField F) (ResidueField K)).injective p).mp inferInstance
  exact ringChar.eq (ResidueField K) p

namespace PrimeCyclicExtension

section LowerBreakBoundary

variable (F K : Type*) [Field F] [Field K]
  [ValuativeRel F] [TopologicalSpace F] [IsNonarchimedeanLocalField F]
  [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
  [Algebra F K] [ValuativeExtension F K]
  [Module.Finite F K] [IsGalois F K]

/-- Minimal one-break boundary data at a manuscript-style nonnegative lower index.  The full
profile is deliberately not duplicated in this predicate. -/
def IsLowerBreak (t : ℕ) : Prop :=
  lowerRamificationGroup F K (t : ℤ) = ⊤ ∧
    lowerRamificationGroup F K ((t : ℤ) + 1) = ⊥

omit [IsGalois F K] in
/-- The lower filtration is full at and below a supplied break. -/
theorem lowerRamificationGroup_eq_top_of_le_break
    {t : ℕ} (ht : IsLowerBreak F K t) {i : ℤ} (hi : i ≤ (t : ℤ)) :
    lowerRamificationGroup F K i = ⊤ := by
  apply eq_top_iff.mpr
  rw [← ht.1]
  exact lowerRamificationGroup_antitone F K hi

omit [IsGalois F K] in
/-- The lower filtration is trivial strictly above a supplied break. -/
theorem lowerRamificationGroup_eq_bot_of_break_lt
    {t : ℕ} (ht : IsLowerBreak F K t) {i : ℤ} (hi : (t : ℤ) < i) :
    lowerRamificationGroup F K i = ⊥ :=
  lowerRamificationGroup_eq_bot_of_ge F K ht.2 (by omega)

end LowerBreakBoundary

section LowerFiltration

variable (F K : Type*) [Field F] [Field K]
  [ValuativeRel F] [TopologicalSpace F] [IsNonarchimedeanLocalField F]
  [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
  [Algebra F K] [ValuativeExtension F K]
  [Module.Free F K] [Module.Finite F K]
  [PrimeCyclicExtension F K]

/-- Every lower ramification group is trivial or the full Galois group.  This uses only prime
cardinality and the canonical lower filtration. -/
theorem lowerRamificationGroup_eq_bot_or_eq_top (i : ℤ) :
    lowerRamificationGroup F K i = ⊥ ∨ lowerRamificationGroup F K i = ⊤ :=
  subgroup_eq_bot_or_eq_top F K (lowerRamificationGroup F K i)

/-- Exact full-group profile associated with a supplied lower break. -/
theorem lowerRamificationGroup_eq_top_iff_le_break
    {t : ℕ} (ht : IsLowerBreak F K t) (i : ℤ) :
    lowerRamificationGroup F K i = ⊤ ↔ i ≤ (t : ℤ) := by
  constructor
  · intro htop
    by_contra hi
    have hbot := lowerRamificationGroup_eq_bot_of_break_lt F K ht (by omega : (t : ℤ) < i)
    exact galoisSubgroup_top_ne_bot F K (htop.symm.trans hbot)
  · exact lowerRamificationGroup_eq_top_of_le_break F K ht

/-- Exact trivial-group profile associated with a supplied lower break. -/
theorem lowerRamificationGroup_eq_bot_iff_break_lt
    {t : ℕ} (ht : IsLowerBreak F K t) (i : ℤ) :
    lowerRamificationGroup F K i = ⊥ ↔ (t : ℤ) < i := by
  constructor
  · intro hbot
    by_contra hi
    have htop := lowerRamificationGroup_eq_top_of_le_break F K ht (by omega : i ≤ (t : ℤ))
    exact galoisSubgroup_top_ne_bot F K (htop.symm.trans hbot)
  · exact lowerRamificationGroup_eq_bot_of_break_lt F K ht

/-- A nonnegative lower break, when supplied, is unique. -/
theorem isLowerBreak_unique {t u : ℕ}
    (ht : IsLowerBreak F K t) (hu : IsLowerBreak F K u) : t = u := by
  have hut : (u : ℤ) ≤ (t : ℤ) :=
    (lowerRamificationGroup_eq_top_iff_le_break F K ht (u : ℤ)).mp hu.1
  have htu : (t : ℤ) ≤ (u : ℤ) :=
    (lowerRamificationGroup_eq_top_iff_le_break F K hu (t : ℤ)).mp ht.1
  exact_mod_cast le_antisymm htu hut

/-- The chosen cyclic generator lies in the exact shell at every supplied lower break. -/
theorem generator_mem_break_and_not_mem_succ
    {t : ℕ} (ht : IsLowerBreak F K t) :
    generator F K ∈ lowerRamificationGroup F K (t : ℤ) ∧
      generator F K ∉ lowerRamificationGroup F K ((t : ℤ) + 1) := by
  constructor
  · rw [ht.1]
    trivial
  · rw [ht.2, Subgroup.mem_bot]
    exact generator_ne_one F K

/-- If `G₀` is explicitly known to be the full Galois group, the prime-order lower filtration
has a unique nonnegative break.  The premise is intentionally explicit: deriving it from
ramifiedness or total ramification belongs to the prime-degree dichotomy node. -/
theorem existsUnique_isLowerBreak_of_zero_eq_top
    (hzero : lowerRamificationGroup F K 0 = ⊤) :
    ∃! t : ℕ, IsLowerBreak F K t := by
  classical
  let P : ℕ → Prop := fun n => lowerRamificationGroup F K (n : ℤ) = ⊥
  have hP : ∃ n : ℕ, P n := by
    obtain ⟨i, hi0, hi⟩ := exists_nonnegative_lowerRamificationGroup_eq_bot F K
    refine ⟨i.toNat, ?_⟩
    simpa [P, Int.toNat_of_nonneg hi0] using hi
  let n : ℕ := Nat.find hP
  have hn : P n := Nat.find_spec hP
  have hnpos : 0 < n := by
    by_contra hnpos
    have hnzero : n = 0 := Nat.eq_zero_of_not_pos hnpos
    rw [hnzero] at hn
    exact galoisSubgroup_top_ne_bot F K (hzero.symm.trans hn)
  let t : ℕ := n - 1
  have htlt : t < n := by
    dsimp only [t]
    omega
  have ht_not_bot : lowerRamificationGroup F K (t : ℤ) ≠ ⊥ := by
    intro htbot
    exact Nat.find_min hP htlt htbot
  have ht_top : lowerRamificationGroup F K (t : ℤ) = ⊤ := by
    rcases lowerRamificationGroup_eq_bot_or_eq_top F K (t : ℤ) with htbot | htop
    · exact (ht_not_bot htbot).elim
    · exact htop
  have ht_succ_bot : lowerRamificationGroup F K ((t : ℤ) + 1) = ⊥ := by
    have htn : t + 1 = n := by
      dsimp only [t]
      omega
    have hcast : (t : ℤ) + 1 = (n : ℤ) := by exact_mod_cast htn
    rw [hcast]
    exact hn
  refine ⟨t, ⟨ht_top, ht_succ_bot⟩, ?_⟩
  intro u hu
  exact isLowerBreak_unique F K hu ⟨ht_top, ht_succ_bot⟩

/-- The canonical nonnegative lower break selected from the explicit hypothesis `G₀ = G`. -/
noncomputable def lowerBreakIndex
    (hzero : lowerRamificationGroup F K 0 = ⊤) : ℕ :=
  (existsUnique_isLowerBreak_of_zero_eq_top F K hzero).choose

/-- The selected lower-break index satisfies the minimal boundary predicate. -/
theorem lowerBreakIndex_isLowerBreak
    (hzero : lowerRamificationGroup F K 0 = ⊤) :
    IsLowerBreak F K (lowerBreakIndex F K hzero) :=
  (existsUnique_isLowerBreak_of_zero_eq_top F K hzero).choose_spec.1

/-- Any supplied nonnegative break equals the canonical selected index. -/
theorem lowerBreakIndex_eq
    (hzero : lowerRamificationGroup F K 0 = ⊤)
    {t : ℕ} (ht : IsLowerBreak F K t) :
    lowerBreakIndex F K hzero = t :=
  isLowerBreak_unique F K (lowerBreakIndex_isLowerBreak F K hzero) ht

end LowerFiltration

end PrimeCyclicExtension

end LanglandsFirstMainLemma
