import LanglandsFirstMainLemma.FiniteField.HasseFunction
import LanglandsFirstMainLemma.FiniteField.EulerProduct
import LanglandsFirstMainLemma.LocalField.Extension

/-!
# The Hasse-function lift

This file proves the finite-field lift formula by applying the reusable Euler-product
identity to the Hasse polynomial weight.  The quadratic correction is the elementary
symmetric sum indexed by **unordered** pairs of distinct embeddings.  If the minimal
polynomial of `x` has first elementary symmetric coefficients `s` and `e`, and every
conjugate occurs `h` times in the ambient extension, that correction is

`h • e + (h.choose 2 : k) * s ^ 2`.

The binomial coefficient, rather than an ordered off-diagonal sum, is what fixes the
factor of two in every characteristic.
-/

open Polynomial
open scoped BigOperators

namespace LanglandsFirstMainLemma

universe u v

noncomputable section

/-- The number of repetitions of each conjugate of `x` among all base-field embeddings of
the ambient finite field. -/
def hasseEmbeddingMultiplicity (k K : Type*) [Field k] [Field K] [Algebra k K]
    (x : K) : ℕ :=
  Module.finrank (↥(IntermediateField.adjoin k {x})) K

/-- The quadratic correction indexed by unordered pairs of distinct embeddings.

Writing the conjugates belonging to the minimal polynomial of `x` as `ξᵢ`, their
unordered-pair sum is `e = ∑_{i<j} ξᵢξⱼ` and their sum is `s = ∑_i ξᵢ`.
If every conjugate is repeated `h` times, pairs of distinct conjugate values contribute
`h²e`, while equal-value pairs contribute `h.choose 2` times `∑ ξᵢ²`.  Substituting
`∑ ξᵢ² = s² - 2e` simplifies the total, integrally and in every characteristic, to
`h • e + (h.choose 2 : k) * s²`. -/
def hassePairCorrection (k K : Type*) [Field k] [Field K] [Algebra k K]
    (x : K) : k :=
  let h := hasseEmbeddingMultiplicity k K x
  let p := minpoly k x
  h • secondCoeff p + (h.choose 2 : k) * (-p.nextCoeff) ^ 2

/-- The trace lift of a Hasse function, with the unordered-pair quadratic correction. -/
def hasseFunctionLiftValue (k K : Type*) [Field k] [Field K] [Finite K]
    [Algebra k K] {psi : FiniteAddChar k} (phi : HasseFunction k psi) (x : K) : ℂ :=
  phi (residueTrace k K x) * psi (-hassePairCorrection k K x)

/-- The minimal polynomial, regarded as a monic polynomial. -/
def hasseMinpolyMonic (k K : Type*) [Field k] [Field K] [Algebra k K]
    [Algebra.IsAlgebraic k K] (x : K) : MonicPolynomial k :=
  ⟨minpoly k x, minpoly.monic (Algebra.IsIntegral.isIntegral x)⟩

/-- The first coefficient of a power of a monic polynomial. -/
theorem monic_nextCoeff_pow {R : Type*} [CommRing R]
    (p : R[X]) (hp : p.Monic) (n : ℕ) :
    (p ^ n).nextCoeff = (n : R) * p.nextCoeff := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [pow_succ, monic_firstCoeff_mul (hp.pow n) hp, ih]
      push_cast
      ring

/-- The second coefficient of a power of a monic polynomial.  Its quadratic term is
indexed by unordered pairs, hence the coefficient `n.choose 2`. -/
theorem monic_secondCoeff_pow {R : Type*} [CommRing R]
    (p : R[X]) (hp : p.Monic) (n : ℕ) :
    secondCoeff (p ^ n) =
      (n : R) * secondCoeff p + (n.choose 2 : R) * p.nextCoeff ^ 2 := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [pow_succ, monic_secondCoeff_mul (hp.pow n) hp, ih,
        monic_nextCoeff_pow p hp n]
      rw [Nat.choose_succ_succ' n 1, Nat.choose_one_right]
      push_cast
      ring

/-- The characteristic polynomial of a block-diagonal matrix is the product of the
characteristic polynomials of its blocks. -/
private theorem Matrix.charpoly_blockDiagonal_eq_prod
    {R : Type*} [CommRing R]
    {m o : Type*} [Fintype m] [DecidableEq m] [Fintype o] [DecidableEq o]
    (M : o → Matrix m m R) :
    (Matrix.blockDiagonal M).charpoly = ∏ i, (M i).charpoly := by
  rw [Matrix.charpoly]
  have hcharmatrix :
      Matrix.charmatrix (Matrix.blockDiagonal M) =
        Matrix.blockDiagonal (fun i ↦ Matrix.charmatrix (M i)) := by
    apply Matrix.ext
    rintro ⟨a, i⟩ ⟨b, j⟩
    by_cases hab : a = b <;> by_cases hij : i = j <;>
      simp [Matrix.blockDiagonal_apply, hab, hij]
  rw [hcharmatrix, Matrix.det_blockDiagonal]
  rfl

/-- The characteristic polynomial of multiplication by `x` is its minimal polynomial
repeated once for each basis element over the simple subextension generated by `x`. -/
theorem lmul_charpoly_eq_minpoly_pow
    (k K : Type*) [Field k] [Field K] [Algebra k K]
    [FiniteDimensional k K] (x : K) :
    (Algebra.lmul k K x).charpoly =
      (minpoly k x) ^ hasseEmbeddingMultiplicity k K x := by
  let E := ↥(IntermediateField.adjoin k {x})
  let xE : E :=
    ⟨x, IntermediateField.subset_adjoin k {x} (Set.mem_singleton x)⟩
  let pb : PowerBasis k E :=
    IntermediateField.adjoin.powerBasis (Algebra.IsIntegral.isIntegral x)
  let bK := Module.Free.chooseBasis E K
  letI := Fintype.ofFinite (Module.Free.ChooseBasisIndex E K)
  letI := Classical.decEq (Module.Free.ChooseBasisIndex E K)
  have hx : algebraMap E K xE = x := rfl
  have hgen : pb.gen = xE := by
    simp only [pb, xE, E, IntermediateField.adjoin.powerBasis_gen]
    rfl
  have hmin : minpoly k xE = minpoly k x := by
    rw [show xE = IntermediateField.AdjoinSimple.gen k x by
      apply Subtype.ext
      rfl]
    exact IntermediateField.minpoly_gen k x
  have hblock :
      Algebra.leftMulMatrix (pb.basis.smulTower bK) x =
        Matrix.blockDiagonal (fun _ ↦ Algebra.leftMulMatrix pb.basis xE) := by
    calc
      Algebra.leftMulMatrix (pb.basis.smulTower bK) x =
          Algebra.leftMulMatrix (pb.basis.smulTower bK) (algebraMap E K xE) := by
        exact congrArg (Algebra.leftMulMatrix (pb.basis.smulTower bK)) hx.symm
      _ = Matrix.blockDiagonal (fun _ ↦ Algebra.leftMulMatrix pb.basis xE) :=
        Algebra.smulTower_leftMulMatrix_algebraMap pb.basis bK xE
  calc
    (Algebra.lmul k K x).charpoly =
        (Algebra.leftMulMatrix (pb.basis.smulTower bK) x).charpoly := by
      exact (LinearMap.charpoly_toMatrix (Algebra.lmul k K x)
        (pb.basis.smulTower bK)).symm
    _ = (Matrix.blockDiagonal (fun _ ↦
          Algebra.leftMulMatrix pb.basis xE)).charpoly := by rw [hblock]
    _ = ∏ _ : Module.Free.ChooseBasisIndex E K,
          (Algebra.leftMulMatrix pb.basis xE).charpoly := by
      exact Matrix.charpoly_blockDiagonal_eq_prod _
    _ = ∏ _ : Module.Free.ChooseBasisIndex E K, minpoly k x := by
      apply Finset.prod_congr rfl
      intro i hi
      rw [← hgen, charpoly_leftMulMatrix, hgen, hmin]
    _ = (minpoly k x) ^ Module.finrank E K := by
      rw [Finset.prod_const, Finset.card_univ, Module.finrank_eq_card_basis bK]
    _ = (minpoly k x) ^ hasseEmbeddingMultiplicity k K x := rfl

/-- The unordered-pair correction is exactly the second coefficient of the repeated
minimal polynomial. -/
theorem hassePairCorrection_eq_secondCoeff_minpoly_pow
    (k K : Type*) [Field k] [Field K] [Algebra k K] [Algebra.IsAlgebraic k K]
    (x : K) :
    hassePairCorrection k K x =
      secondCoeff ((minpoly k x) ^ hasseEmbeddingMultiplicity k K x) := by
  rw [monic_secondCoeff_pow (minpoly k x)
    (minpoly.monic (Algebra.IsIntegral.isIntegral x))]
  simp only [hassePairCorrection, nsmul_eq_mul]
  ring

/-- The unordered-pair correction is the second coefficient of the characteristic
polynomial of multiplication by the element. -/
theorem hassePairCorrection_eq_secondCoeff_charpoly
    (k K : Type*) [Field k] [Field K] [Algebra k K] [FiniteDimensional k K]
    (x : K) :
    hassePairCorrection k K x = secondCoeff (Algebra.lmul k K x).charpoly := by
  rw [lmul_charpoly_eq_minpoly_pow]
  exact hassePairCorrection_eq_secondCoeff_minpoly_pow k K x

/-- The correction is the second elementary symmetric coefficient of multiplication by
the element, i.e. the coefficient indexed by unordered pairs. -/
theorem hassePairCorrection_eq_elementarySymmetric_two
    (k K : Type*) [Field k] [Field K] [Algebra k K] [FiniteDimensional k K]
    (x : K) :
    hassePairCorrection k K x = elementarySymmetric k K 2 x := by
  rw [hassePairCorrection_eq_secondCoeff_charpoly]
  by_cases htwo : 2 ≤ Module.finrank k K
  · rw [elementarySymmetric, if_pos htwo]
    simp only [Even.neg_one_pow (by decide : Even 2), one_mul]
    rw [secondCoeff_eq_coeff_of_two_le _ (by
      rw [LinearMap.charpoly_natDegree]
      exact htwo)]
    rw [LinearMap.charpoly_natDegree]
  · rw [elementarySymmetric, if_neg htwo]
    rw [secondCoeff_eq_zero_of_natDegree_lt_two]
    rw [LinearMap.charpoly_natDegree]
    omega

private theorem Multiset.esymm_two_cons
    {R : Type*} [CommRing R] (a : R) (s : Multiset R) :
    (a ::ₘ s).esymm 2 = s.esymm 2 + a * s.sum := by
  simp [Multiset.esymm, Multiset.powersetCard_cons, Multiset.sum_add,
    Multiset.powersetCard_one]
  simpa using
    (Multiset.sum_map_mul_left (s := s) (f := fun x : R ↦ x) (a := a))

/-- Polarization of the second elementary symmetric function.  The use of `esymm 2`
means that every unordered pair occurs exactly once. -/
theorem Finset.esymm_two_map_add
    {ι R : Type*} [CommRing R] (s : Finset ι) (f g : ι → R) :
    (s.val.map (fun i ↦ f i + g i)).esymm 2 =
      (s.val.map f).esymm 2 + (s.val.map g).esymm 2 +
        (∑ i ∈ s, f i) * (∑ i ∈ s, g i) - ∑ i ∈ s, f i * g i := by
  classical
  induction s using Finset.induction_on with
  | empty => simp [Multiset.esymm]
  | @insert a s ha ih =>
      rw [← Finset.cons_eq_insert a s ha]
      simp only [Finset.cons_val, Multiset.map_cons, Multiset.esymm_two_cons,
        Finset.sum_cons, ih, ← Finset.sum_eq_multiset_sum,
        Finset.sum_add_distrib]
      ring

/-- The unordered-pair sum of all Galois conjugates of an element. -/
def hasseGaloisPairSum
    (k K : Type*) [Field k] [Field K] [Algebra k K]
    [FiniteDimensional k K] (x : K) : K :=
  (galoisConjugates k K x).esymm 2

/-- The unordered Galois-pair sum has the manuscript's exact polarization law. -/
theorem hasseGaloisPairSum_add
    (k K : Type*) [Field k] [Field K] [Algebra k K]
    [FiniteDimensional k K] [IsGalois k K] (x y : K) :
    hasseGaloisPairSum k K (x + y) =
      hasseGaloisPairSum k K x + hasseGaloisPairSum k K y +
        algebraMap k K (trace k K x) * algebraMap k K (trace k K y) -
          algebraMap k K (trace k K (x * y)) := by
  have h := Finset.esymm_two_map_add
    (Finset.univ : Finset Gal(K/k)) (fun σ ↦ σ x) (fun σ ↦ σ y)
  have hx : (∑ σ : Gal(K/k), σ x) = algebraMap k K (trace k K x) := by
    simpa [galoisConjugates, galoisConjugate] using galoisConjugates_sum k K x
  have hy : (∑ σ : Gal(K/k), σ y) = algebraMap k K (trace k K y) := by
    simpa [galoisConjugates, galoisConjugate] using galoisConjugates_sum k K y
  have hxy : (∑ σ : Gal(K/k), σ (x * y)) =
      algebraMap k K (trace k K (x * y)) := by
    simpa [galoisConjugates, galoisConjugate] using
      galoisConjugates_sum k K (x * y)
  have hdiag : (∑ σ : Gal(K/k), σ x * σ y) =
      algebraMap k K (trace k K (x * y)) := by
    rw [← hxy]
    apply Finset.sum_congr rfl
    intro σ _
    exact (σ.map_mul x y).symm
  simpa [hasseGaloisPairSum, galoisConjugates, galoisConjugate,
    hx, hy, hxy, hdiag] using h

private theorem hasse_stabilizer_eq_fixingSubgroup
    (k K : Type*) [Field k] [Field K] [Algebra k K] (x : K) :
    MulAction.stabilizer Gal(K/k) x =
      (IntermediateField.adjoin k {x}).fixingSubgroup := by
  ext σ
  rw [MulAction.mem_stabilizer_iff,
    IntermediateField.mem_fixingSubgroup_iff]
  constructor
  · intro hx y hy
    have heq :
        σ.toAlgHom.comp (IntermediateField.adjoin k {x}).val =
          (IntermediateField.adjoin k {x}).val := by
      apply IntermediateField.adjoin_algHom_ext k
      intro z hz
      have hzx : z = x := Set.mem_singleton_iff.mp hz
      subst z
      exact hx
    exact congrArg
      (fun f : (↥(IntermediateField.adjoin k {x})) →ₐ[k] K ↦ f ⟨y, hy⟩) heq
  · intro h
    exact h x (IntermediateField.subset_adjoin k {x} (Set.mem_singleton x))

private theorem hasse_stabilizer_card
    (k K : Type*) [Field k] [Field K] [Algebra k K]
    [FiniteDimensional k K] [IsGalois k K] (x : K) :
    Nat.card (MulAction.stabilizer Gal(K/k) x) =
      hasseEmbeddingMultiplicity k K x := by
  rw [hasse_stabilizer_eq_fixingSubgroup]
  exact IsGalois.card_fixingSubgroup_eq_finrank
    (F := k) (E := K) (IntermediateField.adjoin k {x})

private noncomputable instance hasseOrbitFintype
    (k K : Type*) [Field k] [Field K] [Algebra k K]
    [FiniteDimensional k K] (x : K) :
    Fintype (MulAction.orbit Gal(K/k) x) :=
  (Finite.finite_mulAction_orbit x).fintype

private noncomputable instance hasseStabilizerFintype
    (k K : Type*) [Field k] [Field K] [Algebra k K]
    [FiniteDimensional k K] (x : K) :
    Fintype (MulAction.stabilizer Gal(K/k) x) :=
  Fintype.ofFinite _

private theorem hasse_prod_galois_eq_prod_orbit_pow
    (k K R : Type*) [Field k] [Field K] [Algebra k K]
    [FiniteDimensional k K] [IsGalois k K] [CommMonoid R]
    (x : K) (f : K → R) :
    (∏ σ : Gal(K/k), f (σ x)) =
    (∏ z : MulAction.orbit Gal(K/k) x, f z.1) ^
        hasseEmbeddingMultiplicity k K x := by
  let e := MulAction.orbitProdStabilizerEquivGroup Gal(K/k) x
  calc
    (∏ σ : Gal(K/k), f (σ x)) =
        ∏ p : MulAction.orbit Gal(K/k) x ×
            MulAction.stabilizer Gal(K/k) x, f p.1.1 := by
      apply Fintype.prod_equiv e.symm
      intro σ
      congr 1
    _ = ∏ z : MulAction.orbit Gal(K/k) x,
          ∏ _s : MulAction.stabilizer Gal(K/k) x, f z.1 := by
      rw [Fintype.prod_prod_type]
    _ = ∏ z : MulAction.orbit Gal(K/k) x,
          f z.1 ^ Nat.card (MulAction.stabilizer Gal(K/k) x) := by
      apply Finset.prod_congr rfl
      intro z hz
      rw [Finset.prod_const, Finset.card_univ, Nat.card_eq_fintype_card]
    _ = (∏ z : MulAction.orbit Gal(K/k) x, f z.1) ^
          Nat.card (MulAction.stabilizer Gal(K/k) x) := by
      rw [Finset.prod_pow]
    _ = (∏ z : MulAction.orbit Gal(K/k) x, f z.1) ^
          hasseEmbeddingMultiplicity k K x := by
      rw [hasse_stabilizer_card]

private theorem hasse_galoisOrbit_eq_conjRootCarrier
    (k K : Type*) [Field k] [Field K] [Algebra k K]
    [FiniteDimensional k K] [IsGalois k K] (x : K) :
    MulAction.orbit Gal(K/k) x = (ConjRootClass.mk k x).carrier := by
  ext y
  rw [ConjRootClass.mem_carrier, ConjRootClass.mk_eq_mk]
  rw [isConjRoot_def, Normal.minpoly_eq_iff_mem_orbit]

/-- The product indexed by all Galois embeddings is the minimal polynomial repeated by
the stabilizer size.  This retains the multiplicities needed for unordered pairs. -/
theorem hasseGaloisLinearFactorProduct_eq_minpoly_pow
    (k K : Type*) [Field k] [Fintype k] [Field K] [Fintype K]
    [Algebra k K] (x : K) :
    (∏ σ : Gal(K/k), (X - C (σ x))) =
      ((minpoly k x).map (algebraMap k K)) ^
        hasseEmbeddingMultiplicity k K x := by
  classical
  let O := MulAction.orbit Gal(K/k) x
  have horbit : O = (ConjRootClass.mk k x).carrier :=
    hasse_galoisOrbit_eq_conjRootCarrier k K x
  let oe : O ≃ (ConjRootClass.mk k x).carrier := Equiv.setCongr horbit
  calc
    (∏ σ : Gal(K/k), (X - C (σ x))) =
        (∏ y : O, (X - C y.1)) ^ hasseEmbeddingMultiplicity k K x :=
      hasse_prod_galois_eq_prod_orbit_pow k K K[X] x (fun y ↦ X - C y)
    _ = (∏ y : (ConjRootClass.mk k x).carrier,
          (X - C y.1)) ^ hasseEmbeddingMultiplicity k K x := by
      congr 1
      exact oe.prod_comp (fun y ↦ X - C y.1)
    _ = (∏ y ∈ (ConjRootClass.mk k x).carrier.toFinset,
          (X - C y)) ^ hasseEmbeddingMultiplicity k K x := by
      congr 1
      simpa using (Finset.prod_set_coe
        (f := fun y : K ↦ X - C y) (ConjRootClass.mk k x).carrier)
    _ = ((minpoly k x).map (algebraMap k K)) ^
          hasseEmbeddingMultiplicity k K x := by
      have hminprod :=
        ConjRootClass.minpoly.map_eq_prod (ConjRootClass.mk k x)
      simp only [ConjRootClass.minpoly_mk] at hminprod
      rw [hminprod]

/-- The minpoly formula for the correction is exactly the unordered-pair sum over all
Galois embeddings, including their correct multiplicities. -/
theorem algebraMap_hassePairCorrection_eq_hasseGaloisPairSum
    (k K : Type*) [Field k] [Fintype k] [Field K] [Fintype K]
    [Algebra k K] (x : K) :
    algebraMap k K (hassePairCorrection k K x) = hasseGaloisPairSum k K x := by
  classical
  let s := galoisConjugates k K x
  have hcard : s.card = Module.finrank k K :=
    galoisConjugates_card k K x
  by_cases htwo : 2 ≤ Module.finrank k K
  · have hpoly :
        (Algebra.lmul k K x).charpoly.map (algebraMap k K) =
          (s.map fun y ↦ X - C y).prod := by
      rw [lmul_charpoly_eq_minpoly_pow, Polynomial.map_pow,
        ← hasseGaloisLinearFactorProduct_eq_minpoly_pow k K x]
      simp only [s, galoisConjugates, galoisConjugate,
        Multiset.map_map, ← Finset.prod_eq_multiset_prod]
      rfl
    have hcoeff := congrArg
      (fun p : K[X] ↦ p.coeff (Module.finrank k K - 2)) hpoly
    rw [Polynomial.coeff_map] at hcoeff
    have hk : Module.finrank k K - 2 ≤ s.card := by
      rw [hcard]
      exact Nat.sub_le _ _
    rw [Multiset.prod_X_sub_C_coeff s
      (k := Module.finrank k K - 2) hk] at hcoeff
    rw [hcard, Nat.sub_sub_self htwo] at hcoeff
    simp only [Even.neg_one_pow (by decide : Even 2), one_mul] at hcoeff
    rw [hassePairCorrection_eq_secondCoeff_charpoly,
      secondCoeff_eq_coeff_of_two_le _ (by
        rw [LinearMap.charpoly_natDegree]
        exact htwo), LinearMap.charpoly_natDegree]
    exact hcoeff
  · have hlt : Module.finrank k K < 2 := Nat.lt_of_not_ge htwo
    rw [hassePairCorrection_eq_elementarySymmetric_two,
      elementarySymmetric_of_finrank_lt k K hlt, map_zero]
    change 0 = s.esymm 2
    symm
    rw [Multiset.esymm, Multiset.powersetCard_eq_empty 2 (by
      rw [hcard]
      exact hlt)]
    rfl

/-- The minpoly correction obeys the polarization law for the unordered embedding-pair
sum.  Trace and multiplication both point from `K` down to `k`. -/
theorem hassePairCorrection_add
    (k K : Type*) [Field k] [Fintype k] [Field K] [Fintype K]
    [Algebra k K] (x y : K) :
    hassePairCorrection k K (x + y) =
      hassePairCorrection k K x + hassePairCorrection k K y +
        residueTrace k K x * residueTrace k K y - residueTrace k K (x * y) := by
  apply (algebraMap k K).injective
  simp only [map_add, map_mul, map_sub,
    algebraMap_hassePairCorrection_eq_hasseGaloisPairSum]
  exact hasseGaloisPairSum_add k K x y

/-- The lifted value satisfies the Hasse functional equation over the extension field. -/
theorem hasseFunctionLiftValue_map_add
    (k K : Type*) [Field k] [Fintype k] [Field K] [Fintype K]
    [Algebra k K] {psi : FiniteAddChar k} (phi : HasseFunction k psi)
    (x y : K) :
    hasseFunctionLiftValue k K phi (x + y) =
      hasseFunctionLiftValue k K phi x * hasseFunctionLiftValue k K phi y *
        traceAddChar k K psi (x * y) := by
  change
    phi (trace k K (x + y)) * psi (-hassePairCorrection k K (x + y)) = _
  rw [(trace k K).map_add x y, hassePairCorrection_add, phi.map_add]
  simp only [traceAddChar_apply]
  rw [show
    -(hassePairCorrection k K x + hassePairCorrection k K y +
        residueTrace k K x * residueTrace k K y - residueTrace k K (x * y)) =
      -hassePairCorrection k K x +
        (-hassePairCorrection k K y +
          (-(residueTrace k K x * residueTrace k K y) +
            residueTrace k K (x * y))) by ring,
    psi.map_add_eq_mul, psi.map_add_eq_mul, psi.map_add_eq_mul]
  have hcancel :
      psi (residueTrace k K x * residueTrace k K y) *
          psi (-(residueTrace k K x * residueTrace k K y)) = 1 := by
    rw [← psi.map_add_eq_mul]
    simp
  calc
    (phi (residueTrace k K x) * phi (residueTrace k K y) *
          psi (residueTrace k K x * residueTrace k K y)) *
        (psi (-hassePairCorrection k K x) *
          (psi (-hassePairCorrection k K y) *
            (psi (-(residueTrace k K x * residueTrace k K y)) *
              psi (residueTrace k K (x * y))))) =
        (phi (residueTrace k K x) * psi (-hassePairCorrection k K x)) *
          (phi (residueTrace k K y) * psi (-hassePairCorrection k K y)) *
          ((psi (residueTrace k K x * residueTrace k K y) *
              psi (-(residueTrace k K x * residueTrace k K y))) *
            psi (residueTrace k K (x * y))) := by ring
    _ =
        (phi (residueTrace k K x) * psi (-hassePairCorrection k K x)) *
          (phi (residueTrace k K y) * psi (-hassePairCorrection k K y)) *
          psi (residueTrace k K (x * y)) := by rw [hcancel, one_mul]

/-- The trace lift, packaged as a Hasse function for the trace-pulled additive
character. -/
def hasseFunctionTraceLift
    (k K : Type*) [Field k] [Fintype k] [Field K] [Fintype K]
    [Algebra k K] {psi : FiniteAddChar k} (phi : HasseFunction k psi) :
    HasseFunction K (traceAddChar k K psi) where
  toFun := hasseFunctionLiftValue k K phi
  ne_zero' x := by
    change phi (residueTrace k K x) * psi (-hassePairCorrection k K x) ≠ 0
    exact mul_ne_zero (phi.ne_zero _) (AddChar.val_isUnit psi _).ne_zero
  map_add' := hasseFunctionLiftValue_map_add k K phi

@[simp]
theorem hasseFunctionTraceLift_apply
    (k K : Type*) [Field k] [Fintype k] [Field K] [Fintype K]
    [Algebra k K] {psi : FiniteAddChar k} (phi : HasseFunction k psi) (x : K) :
    hasseFunctionTraceLift k K phi x = hasseFunctionLiftValue k K phi x :=
  rfl

/-- The trace is the negative first coefficient of the repeated minimal polynomial. -/
theorem residueTrace_eq_neg_nextCoeff_minpoly_pow
    (k K : Type*) [Field k] [Field K] [Finite K] [Algebra k K] (x : K) :
    residueTrace k K x =
      -((minpoly k x) ^ hasseEmbeddingMultiplicity k K x).nextCoeff := by
  rw [monic_nextCoeff_pow (minpoly k x)
    (minpoly.monic (Algebra.IsIntegral.isIntegral x))]
  change Algebra.trace k K x = _
  rw [trace_eq_finrank_mul_minpoly_nextCoeff k x]
  simp only [hasseEmbeddingMultiplicity]
  ring

/-- The Hasse polynomial weight of a monic power is the corresponding power of the
weight. -/
theorem hassePolynomialWeight_pow
    {k : Type*} [Field k] {psi : FiniteAddChar k}
    (phi : HasseFunction k psi) (p : k[X]) (hp : p.Monic) (n : ℕ) :
    phi (-(p ^ n).nextCoeff) * psi (-secondCoeff (p ^ n)) =
      (phi (-p.nextCoeff) * psi (-secondCoeff p)) ^ n := by
  let pm : MonicPolynomial k := ⟨p, hp⟩
  have h := map_pow
    (hassePolynomialWeight (phi : k → ℂ) psi phi.ne_zero phi.map_add) pm n
  exact h

/-- The explicit unordered-pair correction is precisely the one needed for repeated
closed points. -/
theorem hasse_chooseTwo_correction
    {k : Type*} [Field k] {psi : FiniteAddChar k}
    (phi : HasseFunction k psi) (p : k[X]) (hp : p.Monic) (n : ℕ) :
    phi (-((n : k) * p.nextCoeff)) *
        psi (-((n : k) * secondCoeff p + (n.choose 2 : k) * p.nextCoeff ^ 2)) =
      (phi (-p.nextCoeff) * psi (-secondCoeff p)) ^ n := by
  rw [← monic_nextCoeff_pow p hp n, ← monic_secondCoeff_pow p hp n]
  exact hassePolynomialWeight_pow phi p hp n

/-- Compatibility with a repeated closed point.  This is the exact place where unordered
pairs contribute `h.choose 2`, and `HasseFunction.map_nsmul` cancels that correction. -/
theorem hasseFunctionLiftValue_eq_minpolyWeight_pow
    (k K : Type*) [Field k] [Fintype k] [Field K] [Fintype K]
    [Algebra k K] {psi : FiniteAddChar k} (phi : HasseFunction k psi) (x : K) :
    hasseFunctionLiftValue k K phi x =
      (hassePolynomialWeight phi psi phi.ne_zero phi.map_add
        (hasseMinpolyMonic k K x)) ^ hasseEmbeddingMultiplicity k K x := by
  classical
  let h := hasseEmbeddingMultiplicity k K x
  let p := minpoly k x
  let s : k := -p.nextCoeff
  let e : k := secondCoeff p
  have htrace : residueTrace k K x = h • s := by
    change Algebra.trace k K x = h • s
    rw [trace_eq_finrank_mul_minpoly_nextCoeff k x]
    simp only [h, hasseEmbeddingMultiplicity, s, nsmul_eq_mul]
    ring
  have hphase :
      psi ((h.choose 2 : k) * s ^ 2) *
          psi (-(h • e + (h.choose 2 : k) * s ^ 2)) =
        psi (-e) ^ h := by
    rw [← psi.map_add_eq_mul]
    calc
      psi ((h.choose 2 : k) * s ^ 2 +
          -(h • e + (h.choose 2 : k) * s ^ 2)) =
          psi (h • (-e)) := by
            congr 1
            simp only [nsmul_eq_mul]
            ring
      _ = psi (-e) ^ h := AddChar.map_nsmul_eq_pow psi h (-e)
  rw [hasseFunctionLiftValue, htrace, phi.map_nsmul]
  change
    (phi s ^ h * psi ((h.choose 2 : k) * s ^ 2)) *
        psi (-(h • e + (h.choose 2 : k) * s ^ 2)) =
      (phi s * psi (-e)) ^ h
  rw [mul_pow, ← hphase]
  ring

/-- Monic linear polynomials are parametrized by their constant coefficient. -/
private def monicLinearEquiv (k : Type u) [Field k] :
    MonicPolynomialOfDegree k 1 ≃ k where
  toFun p := p.1.coeff 0
  invFun a := ⟨X + C a, monic_X_add_C a, natDegree_X_add_C a⟩
  left_inv p := by
    apply Subtype.ext
    exact (p.2.1.eq_X_add_C p.2.2).symm
  right_inv a := by simp

/-- The degree-one coefficient of the Hasse polynomial `L`-series is the Hasse sum. -/
theorem degreeSum_hassePolynomialWeight_one
    {k : Type u} [Field k] [Fintype k]
    {psi : FiniteAddChar k} (phi : HasseFunction k psi) :
    MonicWeight.degreeSum
        (hassePolynomialWeight (fun x => phi x) psi
          (fun x => phi.ne_zero x) (fun x y => phi.map_add x y)) 1 =
      phi.sum := by
  classical
  rw [MonicWeight.degreeSum, HasseFunction.sum]
  calc
    (∑ p : MonicPolynomialOfDegree k 1,
        hassePolynomialWeight (fun x => phi x) psi
          (fun x => phi.ne_zero x) (fun x y => phi.map_add x y)
          ⟨p.1, p.2.1⟩) =
        ∑ a : k, phi (-a) := by
      apply Fintype.sum_equiv (monicLinearEquiv k)
      intro p
      rw [hassePolynomialWeight_apply]
      have hp : p.1 = X + C (p.1.coeff 0) := p.2.1.eq_X_add_C p.2.2
      rw [hp, nextCoeff_X_add_C]
      rw [secondCoeff_eq_zero_of_natDegree_lt_two _ (by simp)]
      simp [monicLinearEquiv]
    _ = ∑ x : k, phi x := by
      apply Fintype.sum_equiv (Equiv.neg k)
      intro x
      simp

/-- Add a freely chosen value to the second coefficient of a monic polynomial. -/
private def shiftSecondCoeff
    {k : Type u} [Field k] (n : ℕ) (hn : 2 ≤ n) (c : k)
    (p : MonicPolynomialOfDegree k n) : MonicPolynomialOfDegree k n := by
  let t : k[X] := C c * X ^ (n - 2)
  have htdeg : degree t < degree p.1 := by
    rw [degree_eq_natDegree p.2.1.ne_zero, p.2.2]
    have hlt : n - 2 < n := by omega
    exact (degree_C_mul_X_pow_le (n - 2) c).trans_lt
      (WithBot.coe_lt_coe.mpr hlt)
  exact ⟨p.1 + t, p.2.1.add_of_left htdeg,
    (natDegree_add_eq_left_of_degree_lt htdeg).trans p.2.2⟩

@[simp]
private theorem shiftSecondCoeff_val
    {k : Type u} [Field k] (n : ℕ) (hn : 2 ≤ n) (c : k)
    (p : MonicPolynomialOfDegree k n) :
    (shiftSecondCoeff n hn c p : k[X]) = p.1 + C c * X ^ (n - 2) :=
  rfl

private theorem shiftSecondCoeff_neg
    {k : Type u} [Field k] (n : ℕ) (hn : 2 ≤ n) (c : k)
    (p : MonicPolynomialOfDegree k n) :
    shiftSecondCoeff n hn (-c) (shiftSecondCoeff n hn c p) = p := by
  apply Subtype.ext
  simp [shiftSecondCoeff_val]

/-- Shifting the second coefficient is a permutation of exact-degree monic polynomials. -/
private def shiftSecondCoeffEquiv
    {k : Type u} [Field k] (n : ℕ) (hn : 2 ≤ n) (c : k) :
    MonicPolynomialOfDegree k n ≃ MonicPolynomialOfDegree k n where
  toFun := shiftSecondCoeff n hn c
  invFun := shiftSecondCoeff n hn (-c)
  left_inv := shiftSecondCoeff_neg n hn c
  right_inv p := by
    simpa using shiftSecondCoeff_neg n hn (-c) p

private theorem nextCoeff_shiftSecondCoeff
    {k : Type u} [Field k] (n : ℕ) (hn : 2 ≤ n) (c : k)
    (p : MonicPolynomialOfDegree k n) :
    ((shiftSecondCoeff n hn c p : MonicPolynomialOfDegree k n) : k[X]).nextCoeff =
      p.1.nextCoeff := by
  rw [nextCoeff_of_natDegree_pos (show
    0 < (shiftSecondCoeff n hn c p : k[X]).natDegree by
      rw [(shiftSecondCoeff n hn c p).2.2]
      omega)]
  rw [nextCoeff_of_natDegree_pos (show 0 < p.1.natDegree by rw [p.2.2]; omega)]
  rw [(shiftSecondCoeff n hn c p).2.2, p.2.2, shiftSecondCoeff_val, coeff_add,
    coeff_C_mul_X_pow]
  simp [show n - 1 ≠ n - 2 by omega]

private theorem secondCoeff_shiftSecondCoeff
    {k : Type u} [Field k] (n : ℕ) (hn : 2 ≤ n) (c : k)
    (p : MonicPolynomialOfDegree k n) :
    secondCoeff ((shiftSecondCoeff n hn c p : MonicPolynomialOfDegree k n) : k[X]) =
      secondCoeff p.1 + c := by
  rw [secondCoeff_eq_coeff_of_two_le _ (by
    rw [(shiftSecondCoeff n hn c p).2.2]
    exact hn)]
  rw [secondCoeff_eq_coeff_of_two_le _ (by rw [p.2.2]; exact hn)]
  rw [(shiftSecondCoeff n hn c p).2.2, p.2.2, shiftSecondCoeff_val, coeff_add,
    coeff_C_mul_X_pow, if_pos rfl]

/-- Every Hasse polynomial weight sum of degree at least two vanishes.  The proof shifts
the freely varying second coefficient by a value on which `psi` is nontrivial. -/
theorem degreeSum_hassePolynomialWeight_eq_zero
    {k : Type u} [Field k] [Fintype k]
    {psi : FiniteAddChar k} (hpsi : psi ≠ 1)
    (phi : HasseFunction k psi) (n : ℕ) (hn : 2 ≤ n) :
    MonicWeight.degreeSum
        (hassePolynomialWeight (fun x => phi x) psi
          (fun x => phi.ne_zero x) (fun x y => phi.map_add x y)) n = 0 := by
  classical
  let w : MonicWeight k ℂ :=
    hassePolynomialWeight (fun x => phi x) psi
      (fun x => phi.ne_zero x) (fun x y => phi.map_add x y)
  obtain ⟨c, hc⟩ : ∃ c : k, psi (-c) ≠ 1 := by
    by_contra h
    push Not at h
    apply hpsi
    ext x
    simpa using h (-x)
  have hshift (p : MonicPolynomialOfDegree k n) :
      w ⟨(shiftSecondCoeffEquiv n hn c p).1,
          (shiftSecondCoeffEquiv n hn c p).2.1⟩ =
        w ⟨p.1, p.2.1⟩ * psi (-c) := by
    simp only [w, hassePolynomialWeight_apply]
    change phi (-((shiftSecondCoeff n hn c p : MonicPolynomialOfDegree k n) :
        k[X]).nextCoeff) *
        psi (-secondCoeff ((shiftSecondCoeff n hn c p :
          MonicPolynomialOfDegree k n) : k[X])) =
      phi (-p.1.nextCoeff) * psi (-secondCoeff p.1) * psi (-c)
    rw [nextCoeff_shiftSecondCoeff, secondCoeff_shiftSecondCoeff]
    rw [show -(secondCoeff p.1 + c) = -secondCoeff p.1 + -c by ring,
      psi.map_add_eq_mul]
    ring
  have hsum : MonicWeight.degreeSum w n =
      MonicWeight.degreeSum w n * psi (-c) := by
    rw [MonicWeight.degreeSum]
    calc
      (∑ p : MonicPolynomialOfDegree k n, w ⟨p.1, p.2.1⟩) =
          ∑ p : MonicPolynomialOfDegree k n,
            w ⟨(shiftSecondCoeffEquiv n hn c p).1,
              (shiftSecondCoeffEquiv n hn c p).2.1⟩ := by
        simpa using ((shiftSecondCoeffEquiv n hn c).sum_comp
          (fun p : MonicPolynomialOfDegree k n => w ⟨p.1, p.2.1⟩)).symm
      _ = ∑ p : MonicPolynomialOfDegree k n,
            w ⟨p.1, p.2.1⟩ * psi (-c) := by
        apply Finset.sum_congr rfl
        intro p _
        exact hshift p
      _ = (∑ p : MonicPolynomialOfDegree k n, w ⟨p.1, p.2.1⟩) * psi (-c) := by
        rw [Finset.sum_mul]
  have hzero : MonicWeight.degreeSum w n * (1 - psi (-c)) = 0 := by
    calc
      MonicWeight.degreeSum w n * (1 - psi (-c)) =
          MonicWeight.degreeSum w n - MonicWeight.degreeSum w n * psi (-c) := by ring
      _ = 0 := sub_eq_zero.mpr hsum
  exact (mul_eq_zero.mp hzero).resolve_right (sub_ne_zero.mpr hc.symm)

/-- The elements of an extension whose minimal polynomial is a fixed monic irreducible
polynomial. -/
abbrev HasseMinpolyFiber (k K : Type*) [Field k] [Field K] [Algebra k K]
    {d : ℕ} (p : MonicIrreducibleOfDegree k d) :=
  {x : K // minpoly k x = p.1.1}

noncomputable instance hasseMinpolyFiberFintype
    (k K : Type*) [Field k] [Field K] [Fintype K] [Algebra k K]
    {d : ℕ} (p : MonicIrreducibleOfDegree k d) :
    Fintype (HasseMinpolyFiber k K p) :=
  Fintype.ofFinite _

/-- Roots in `K` of a monic irreducible polynomial are the base-field homomorphisms from
its simple root extension to `K`. -/
def hasseMinpolyFiberEquivAlgHom
    (k K : Type*) [Field k] [Field K] [Algebra k K]
  {d : ℕ} (p : MonicIrreducibleOfDegree k d) :
    HasseMinpolyFiber k K p ≃ (AdjoinRoot p.1.1 →ₐ[k] K) where
  toFun x := AdjoinRoot.liftAlgHom p.1.1 (Algebra.ofId k K) x.1 (by
    change Polynomial.aeval x.1 p.1.1 = 0
    simpa only [x.2] using minpoly.aeval k x.1)
  invFun sigma := ⟨sigma (AdjoinRoot.root p.1.1), by
    exact (minpoly.eq_of_irreducible_of_monic p.2
      (AdjoinRoot.aeval_algHom_eq_zero p.1.1 sigma) p.1.2.1).symm⟩
  left_inv x := by
    apply Subtype.ext
    exact AdjoinRoot.liftAlgHom_root p.1.1 (Algebra.ofId k K) x.1 _
  right_inv sigma := by
    exact AdjoinRoot.liftAlgHom_eq_algHom p.1.1 sigma

/-- A degree-`d` closed point has exactly `d` roots in a finite extension whose degree is
divisible by `d`. -/
theorem hasseMinpolyFiber_card
    (k K : Type*) [Field k] [Fintype k] [Field K] [Fintype K] [Algebra k K]
    {d : ℕ} (p : MonicIrreducibleOfDegree k d)
    (hdvd : d ∣ Module.finrank k K) :
    Fintype.card (HasseMinpolyFiber k K p) = d := by
  classical
  letI : Fact (Irreducible p.1.1) := ⟨p.2⟩
  have hp0 : p.1.1 ≠ 0 := p.2.ne_zero
  let pb := AdjoinRoot.powerBasis hp0
  letI : Module.Finite k (AdjoinRoot p.1.1) := pb.finite
  letI : Fintype (AdjoinRoot p.1.1) :=
    Fintype.ofEquiv (Fin pb.dim → k) pb.basis.equivFun.toEquiv.symm
  have hfinrank : Module.finrank k (AdjoinRoot p.1.1) = p.1.1.natDegree :=
    (AdjoinRoot.powerBasis hp0).finrank
  have hadjoin_dvd : Module.finrank k (AdjoinRoot p.1.1) ∣ Module.finrank k K := by
    rw [hfinrank, p.1.2.2]
    exact hdvd
  calc
    Fintype.card (HasseMinpolyFiber k K p) =
        Fintype.card (AdjoinRoot p.1.1 →ₐ[k] K) :=
      Fintype.card_congr (hasseMinpolyFiberEquivAlgHom k K p)
    _ = Module.finrank k (AdjoinRoot p.1.1) :=
      FiniteField.card_algHom_of_finrank_dvd hadjoin_dvd
    _ = d := by rw [hfinrank, p.1.2.2]

/-- Closed points of degrees dividing the extension degree, together with one of their
roots in the extension. -/
abbrev HasseClosedPointIndex
    (k K : Type*) [Field k] [Field K] [Algebra k K] :=
  Σ d : {d : ℕ // d ∈ (Module.finrank k K).divisors},
    Σ p : MonicIrreducibleOfDegree k d.1, HasseMinpolyFiber k K p

/-- Partition a finite field extension by the minimal polynomial of each element. -/
def hasseClosedPointIndexEquiv
    (k K : Type*) [Field k] [Fintype k] [Field K] [Fintype K] [Algebra k K] :
    HasseClosedPointIndex k K ≃ K where
  toFun z := z.2.2.1
  invFun x :=
    ⟨⟨(minpoly k x).natDegree, Nat.mem_divisors.mpr
        ⟨minpoly.degree_dvd (Algebra.IsIntegral.isIntegral x),
          (Module.finrank_pos : 0 < Module.finrank k K).ne'⟩⟩,
      ⟨⟨⟨minpoly k x, minpoly.monic (Algebra.IsIntegral.isIntegral x), rfl⟩,
          minpoly.irreducible (Algebra.IsIntegral.isIntegral x)⟩,
        ⟨x, rfl⟩⟩⟩
  left_inv z := by
    rcases z with
      ⟨⟨d, hd⟩, ⟨⟨⟨p, hpmonic, hpdegree⟩, hpirreducible⟩, ⟨x, hx⟩⟩⟩
    change minpoly k x = p at hx
    subst p
    change (minpoly k x).natDegree = d at hpdegree
    subst d
    rfl
  right_inv x := rfl

/-- In the tower generated by `x`, the quotient of the ambient degree by the minimal
polynomial degree is exactly the embedding multiplicity. -/
theorem hasse_degree_div_eq_embeddingMultiplicity
    (k K : Type*) [Field k] [Fintype k] [Field K] [Fintype K] [Algebra k K]
    (x : K) :
    Module.finrank k K / (minpoly k x).natDegree =
      hasseEmbeddingMultiplicity k K x := by
  let d := (minpoly k x).natDegree
  let h := hasseEmbeddingMultiplicity k K x
  have hxint : IsIntegral k x := Algebra.IsIntegral.isIntegral x
  have hdpos : 0 < d := (minpoly.irreducible hxint).natDegree_pos
  have hprod : d * h = Module.finrank k K := by
    dsimp [d, h, hasseEmbeddingMultiplicity]
    rw [← IntermediateField.adjoin.finrank hxint]
    exact Module.finrank_mul_finrank k (↥(IntermediateField.adjoin k {x})) K
  calc
    Module.finrank k K / d = (h * d) / d := by rw [← hprod, Nat.mul_comm]
    _ = h := Nat.mul_div_left h hdpos

/-- The closed-point power sum of the Hasse polynomial weight is the elementwise sum of
the trace lift.  The factor `d` in the closed-point expression is accounted for by the
`d` roots in each minimal-polynomial fiber. -/
theorem hasseClosedPointPowerSum_eq_liftSum
    (k K : Type*) [Field k] [Fintype k] [Field K] [Fintype K] [Algebra k K]
    {psi : FiniteAddChar k} (phi : HasseFunction k psi) :
    MonicWeight.closedPointPowerSum
        (hassePolynomialWeight (phi : k → ℂ) psi phi.ne_zero phi.map_add)
        (Module.finrank k K) =
      ∑ x : K, hasseFunctionLiftValue k K phi x := by
  classical
  let r := Module.finrank k K
  let w : MonicWeight k ℂ :=
    hassePolynomialWeight (phi : k → ℂ) psi phi.ne_zero phi.map_add
  change MonicWeight.closedPointPowerSum w r =
    ∑ x : K, hasseFunctionLiftValue k K phi x
  unfold MonicWeight.closedPointPowerSum
  calc
    (∑ d ∈ r.divisors,
        (d : ℂ) * ∑ p : MonicIrreducibleOfDegree k d,
          w ⟨p.1.1, p.1.2.1⟩ ^ (r / d)) =
        ∑ d : {d : ℕ // d ∈ r.divisors},
          (d.1 : ℂ) * ∑ p : MonicIrreducibleOfDegree k d.1,
            w ⟨p.1.1, p.1.2.1⟩ ^ (r / d.1) := by
      rw [show (Finset.univ : Finset {d : ℕ // d ∈ r.divisors}) =
          r.divisors.attach from Finset.univ_eq_attach _]
      exact (Finset.sum_attach r.divisors (fun d =>
        (d : ℂ) * ∑ p : MonicIrreducibleOfDegree k d,
          w ⟨p.1.1, p.1.2.1⟩ ^ (r / d))).symm
    _ = ∑ d : {d : ℕ // d ∈ r.divisors},
        ∑ p : MonicIrreducibleOfDegree k d.1,
          ∑ _x : HasseMinpolyFiber k K p,
            w ⟨p.1.1, p.1.2.1⟩ ^ (r / d.1) := by
      apply Finset.sum_congr rfl
      intro d _
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro p _
      have hdvd : d.1 ∣ Module.finrank k K := by
        simpa [r] using (Nat.mem_divisors.mp d.2).1
      have hcard := hasseMinpolyFiber_card k K p hdvd
      calc
        (d.1 : ℂ) * w ⟨p.1.1, p.1.2.1⟩ ^ (r / d.1) =
            (Fintype.card (HasseMinpolyFiber k K p) : ℂ) *
              w ⟨p.1.1, p.1.2.1⟩ ^ (r / d.1) := by rw [hcard]
        _ = ∑ _x : HasseMinpolyFiber k K p,
              w ⟨p.1.1, p.1.2.1⟩ ^ (r / d.1) := by
          simp only [Finset.sum_const, Finset.card_univ, nsmul_eq_mul]
    _ = ∑ z : HasseClosedPointIndex k K,
        w ⟨z.2.1.1.1, z.2.1.1.2.1⟩ ^ (r / z.1.1) := by
      rw [Fintype.sum_sigma]
      apply Finset.sum_congr rfl
      intro d _
      rw [Fintype.sum_sigma]
    _ = ∑ x : K, hasseFunctionLiftValue k K phi x := by
      apply Fintype.sum_equiv (hasseClosedPointIndexEquiv k K)
      intro z
      rcases z with ⟨d, p, x⟩
      dsimp only
      change w ⟨p.1.1, p.1.2.1⟩ ^ (r / d.1) =
        hasseFunctionLiftValue k K phi x.1
      have hdegree : r / d.1 = hasseEmbeddingMultiplicity k K x.1 := by
        have hdenominator : d.1 = (minpoly k x.1).natDegree :=
          p.1.2.2.symm.trans (congrArg Polynomial.natDegree x.2.symm)
        calc
          r / d.1 = Module.finrank k K / (minpoly k x.1).natDegree := by
            exact congrArg (fun m => Module.finrank k K / m) hdenominator
          _ = hasseEmbeddingMultiplicity k K x.1 :=
            hasse_degree_div_eq_embeddingMultiplicity k K x.1
      have hpolynomial :
          hasseMinpolyMonic k K x.1 =
            (⟨p.1.1, p.1.2.1⟩ : MonicPolynomial k) := by
        apply Subtype.ext
        exact x.2
      rw [hasseFunctionLiftValue_eq_minpolyWeight_pow, hdegree, hpolynomial]

/-- **Hasse-function lift.**  For a finite extension `K/k` and a Hasse function with
nontrivial polar additive character, the negative sum of the trace lift is the extension-
degree power of the negative Hasse sum.  Both minus signs and the exponent
`Module.finrank k K` are the manuscript's normalization. -/
theorem hasseFunctionLift
    (k K : Type*) [Field k] [Fintype k] [Field K] [Fintype K] [Algebra k K]
    {psi : FiniteAddChar k} (hpsi : psi ≠ 1) (phi : HasseFunction k psi) :
    -(∑ x : K, hasseFunctionLiftValue k K phi x) =
      (-phi.sum) ^ Module.finrank k K := by
  let w : MonicWeight k ℂ :=
    hassePolynomialWeight (phi : k → ℂ) psi phi.ne_zero phi.map_add
  have hvanish : ∀ n, 2 ≤ n → MonicWeight.degreeSum w n = 0 := by
    intro n hn
    exact degreeSum_hassePolynomialWeight_eq_zero hpsi phi n hn
  have heuler := closedPoint_power_identity w hvanish
    (Module.finrank k K) (Module.finrank_pos : 0 < Module.finrank k K)
  rw [hasseClosedPointPowerSum_eq_liftSum k K phi] at heuler
  rw [degreeSum_hassePolynomialWeight_one phi] at heuler
  exact heuler

end

end LanglandsFirstMainLemma
